AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  UserTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: email
          AttributeType: S
      KeySchema: 
        - 
          AttributeName: email
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: users
  AuthTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: userID
          AttributeType: S
        - 
          AttributeName: authUUID
          AttributeType: S
      KeySchema: 
        - 
          AttributeName: userID
          KeyType: HASH
        - 
          AttributeName: authUUID
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TimeToLiveSpecification:
        AttributeName: expirationTime
        Enabled: true
      TableName: auths