AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  PlayerTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: firstName
          AttributeType: S
        - 
          AttributeName: lastName
          AttributeType: S
        - 
          AttributeName: team
          AttributeType: S
      KeySchema: 
        - 
          AttributeName: firstName
          KeyType: HASH
        - 
          AttributeName: lastName
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes: 
      - 
        IndexName: "teamGSI"
        KeySchema: 
          - 
            AttributeName: team
            KeyType: HASH
        Projection: 
          ProjectionType: ALL
        ProvisionedThroughput: 
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      TableName: players

